[build]
  publish = "dist"
  command = "powershell -ExecutionPolicy Bypass -Command \"Remove-Item -Recurse -Force dist -ErrorAction SilentlyContinue; New-Item -ItemType Directory -Path dist | Out-Null; Copy-Item index.html,manifest.webmanifest,sw.js,privacy.html,hulp.html -Destination dist -ErrorAction SilentlyContinue; robocopy icons dist\\icons /E | Out-Null; robocopy screenshots dist\\screenshots /E | Out-Null; robocopy demo dist\\demo /E | Out-Null; robocopy senioreasebieb dist\\senioreasebieb /E | Out-Null; Set-Content -Path dist\\_redirects -Value '/demo/* /demo/:splat 200`n/senioreasebieb/* /senioreasebieb/:splat 200`n/senioreasebieb /senioreasebieb/ 301`n/* /index.html 200'\""

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/demo/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"

[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json"

[[redirects]]
  from = "/senioreasebieb"
  to = "/senioreasebieb/"
  status = 301

[[redirects]]
  from = "/demo/*"
  to = "/demo/:splat"
  status = 200

[[redirects]]
  from = "/senioreasebieb/*"
  to = "/senioreasebieb/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Force HTTPS redirects
[[redirects]]
  from = "http://seniorease.nl/*"
  to = "https://seniorease.nl/:splat"
  status = 301

[[redirects]]
  from = "http://www.seniorease.nl/*"
  to = "https://seniorease.nl/:splat"
  status = 301
